### ISSUE TITLE
Overlap at first time

### ISSUE THREAD

**Issue by DogeVenci** [WouterFlorijn/vue-stack-grid#5] opened 2019-06-30 05:15 UTC
Item will overlap when the image loads slowly or failed at first time.
Can it add recycle features like [vue-recyclerview](https://github.com/hilongjw/vue-recyclerview)?

**Comment by WouterFlorijn** [comment] 2019-07-02 20:30
@DDogeChan I think there are probably two options:
1. Add a prop `reflowInterval` based on which the stack items are updated periodically until all images are loaded. Should be `undefined` by default, in which case the items are not updated periodically.
2. Update whenever any image is loaded instead of all images (though this might already be the case with `vue-images-loaded`, would have to check).

If you could make a PR for this I could review and merge it.

As for recycle features, I'm not sure. I want this to be a lightweight package without too many additional features. I don't think loading new items should be the responsibility of this package, since it can be added relatively easily by wrapping it in another component that takes care of the infinite scroll and loading features. If many people would request this, I'll consider it. Can you make this into a separate issue, so it can be discussed?

**Comment by LTFENG** [comment] 2019-07-08 01:39
yes. overlap at the first time. can we have an option to load the image (placeholder image / like facebook shimmer effect liked image) ? I like your work as it is the easiest way to implement the pinterest liked layout effect. thanks. hope can be improved for this first time loaded overlapping issue.

![Screenshot 2019-07-08 at 9 36 19 AM](https://user-images.githubusercontent.com/25564882/60777284-27ea9f80-a164-11e9-829d-3521bc86989e.png)

**Comment by DagoGzz** [comment] 2019-07-29 22:40
Did anyone find a solution?

**Comment by LTFENG** [comment] 2019-09-12 00:00
@DDogeChan  What is your solution ? Do you mind to share us ? 

Thank you

**Comment by WouterFlorijn** [comment] 2020-01-01 17:56
Just as a note: One possible solution would be to hide the stack grid using `opacity: 0`, and then set it to 1 once the images are loaded. The `Stack` component emits an `images-loaded` when this happens, so you can listen using something like `@images-loaded="showStackGrid"`.

**Comment by WouterFlorijn** [comment] 2020-01-21 09:46
@DDogeChan I fixed this recently. Could you test it by pulling the git repo? (It's not on npm yet)

**Comment by kheinz57** [comment] 2020-04-27 19:34
@WouterFlorijn I may have the same error (does not show with images from unsplash, but does happen with my own images). As soon as I resize the browser window the layout is getting fixed. 
Other than that your component is really nice and easy to use!

I would like to test you fix but do not know how to do the patch or use the github soure code within npm. I have installed your lib with 'npm install vue-stack-grid' as stated here: https://www.youtube.com/watch?v=-W1A5QNUzSk and https://medium.com/swlh/creating-a-pinterest-style-image-gallery-in-vue-927836b7d173

**Comment by WouterFlorijn** [comment] 2020-04-28 13:25
@kheinz57 for an easy way to test, you can simply edit the files in the `node_modules/vue-stack-grid` folder within your project folder.

Since I already made some changes to hopefully fix the issue, you could simply download the code in this repo as zip (see screenshot), and copy-paste the files into the `node_modules/vue-stack-grid` folder, overwriting the existing files. As long as you don't run `npm install` again after that, you can run your project with these changes. If that works, let me know, then I'll publish it on npm so anyone can update the package and use the fix.

![image](https://user-images.githubusercontent.com/7816704/80491233-baae3200-8962-11ea-94a0-804e34c105fa.png)

**Comment by kheinz57** [comment] 2020-04-28 15:45
@WouterFlorijn: It is working flawlessly now. I have simply manuelly applied the fix in the location you have told me. And to double check went back without fix and the bug showd up again. And with fix again it was working. Thank you for fixing the problem.

**Comment by WouterFlorijn** [comment] 2020-04-28 16:35
@kheinz57 cool! I've published it on npm under version 1.2.0, so you can get it by updating.

I'll close this issue.

**Closed by WouterFlorijn** 2020-04-28 16:35 UTC

**Comment by thinh105** [comment] 2020-07-02 06:15
I still face this problem,

My stack is a list of cards that get data from API and it took a while, then, when load the website, all the card stuck in the beginning,

so my workaround is using a simple v-if to hide the element until the data is present.

Hope it can be fixed in next version

**Comment by WouterFlorijn** [comment] 2020-07-02 08:11
@thinh105 the problem is that you need to call `reflow` when the size of items change. You should be able to do this easily by adding a ref to the `stack` component that's accessible by the component that makes the api call(s) and then call `stackRef.reflow()` when an api call succeeds.

**Comment by thinh105** [comment] 2020-07-02 08:47
> @thinh105 the problem is that you need to call `reflow` when the size of items change. You should be able to do this easily by adding a ref to the `stack` component that's accessible by the component that makes the api call(s) and then call `stackRef.reflow()` when an api call succeeds.

Thank for your help,

I can make it work with something like this 

```js

    methods: {
      async fetchTours() {
        await this.$store.dispatch(FETCH_TOURS);
        this.$refs.feed.$refs.stackRef.reflow();
      },
    },
```
